version: '2'
volumes:
  octoprint-data: {}
services:
  octoprint:
    build: ./octoprint
    restart: always
    volumes:
      - 'octoprint-data:/root/.octoprint'
    privileged: true
    ports:
      - '80:5000'